name: backend test CI

on:
  push:
    branches: [ master, Jlalo01-patch-12 ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: back-end

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 16.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm ci
    - run: DB_CONNECTION_STRING="mongodb+srv://pkanchi:testPassword@testerconnector.wlcl1op.mongodb.net/?retryWrites=true&w=majority" npm run coverage
  
  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: DB_CONNECTION_STRING="mongodb+srv://pkanchi:testPassword@testerconnector.wlcl1op.mongodb.net/?retryWrites=true&w=majority" Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.render.com/deploy/srv-ch8v2rlgk4qeoo09jp6g?key=NF8dTp_o-UE'
        method: 'POST'
