name: cd

on:
  push:
    branches: [ Jlalo01-patch-12 ]

defaults:
  run:
    working-directory: front-end

jobs:
  deployment:
    uses: fjogeleit/http-request-action@master
    
    name: Deploy To Ploi
    
    with:
      url: 'https://ploi.io/webhooks/servers/1/sites/1/deploy?token=xxx'
      method: 'POST'
